### ISSUE TITLE
Issue using latest dependencies

### ISSUE THREAD

**Issue by DanielFran** [pavankjadda/LiquibaseDemo#6]
Using latest version I have NullPointException:
- spring-boot 2.1.5
- liquibase hibernate5 3.7
- liquibase plugin 3.6.3

**Comment by pavankjadda** [comment]
Hey,
I tried with the latest dependencies, I am able to reproduce it. Let me check why it's happening. There must be incompatibilities with the latest liquibase and liquibase-hibernate

**Comment by pavankjadda** [comment]
This seems an issue with liquibase. See https://github.com/liquibase/liquibase-hibernate/issues/198 for more info. Let's wait for the bugfix from the liquibase team and proceed further

**Comment by DanielFran** [comment]
@pavankjadda  Seems that liquibase-hibernate 3.8 is now compatible with liquibase 3.8.0, issue should be fixed now.

**Comment by pavankjadda** [comment]
@DanielFran Let me test the repo with 3.8

**Comment by pavankjadda** [comment]
@DanielFran As you said, this issue still exists in the liquibase-hibernate 3.8. Hope they will fix it soon

**Comment by DanielFran** [comment]
@pavankjadda I created a PR to fix the issue, let's wait...

**Comment by DanielFran** [comment]
@pavankjadda xsd are now available, v 3.8.0 should work properly now

**Comment by pavankjadda** [comment]
I tried with the following versions
```
        <liquibase-maven-plugin.version>3.8.0</liquibase-maven-plugin.version>
        <liquibase-hibernate5.version>3.8</liquibase-hibernate5.version>
```
I still get  the same error
```
[WARNING] Unknown database: Hibernate
[INFO] Performing Diff on database root@localhost @ jdbc:mysql://localhost:3306/liquibasedemo?serverTimezone=UTC (Default Schema: liquibasedemo)
[INFO] Error getting default schema
```

**Comment by DanielFran** [comment]
@pavankjadda  Did you try using spring-boot 2.2 and liquibase 3.8.3?

**Comment by pavankjadda** [comment]
Just now did. I got this error

```
[INFO] Starting Liquibase at Fri, 20 Dec 2019 13:56:47 EST (version 3.8.3 #31 built at Wed Dec 18 04:43:08 UTC 2019)
[INFO] Parsing Liquibase Properties File src/main/resources/liquibase.properties for changeLog parameters
[INFO] Executing on Database: jdbc:mysql://localhost:3306/liquibasedemo
[WARNING] Namespace of the [javax.xml.bind.annotation.XmlSchema] annotation does not match [http://www.hibernate.org/xsd/orm/hbm]. Processing bindings will probably fail.
[INFO] Reading hibernate configuration hibernate:spring:com.liquibasedemo.model?dialect=org.hibernate.dialect.MySQLDialect&diffChangeLogFile=src/main/resources/db/db.changelog-master.xml
[INFO] Found package com.liquibasedemo.model
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.140 s
[INFO] Finished at: 2019-12-20T13:56:47-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.liquibase:liquibase-maven-plugin:3.8.3:diff (diff-profile) on project liquibasedemo: Error setting up or running Liquibase: javax.persistence.PersistenceException: Unable to resolve persistence unit root URL: class path resource [] cannot be resolved to URL because it does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 

```

**Comment by DanielFran** [comment]
New v. 3.8.4 has been created with more fixes

**Comment by pavankjadda** [comment]
@DanielFran  3.8.3 is the latest version available

**Comment by DanielFran** [comment]
@pavankjadda It seems that new version 3.8.7 fixed the issue with the diff
See https://github.com/liquibase/liquibase-hibernate/issues/222

**Comment by pavankjadda** [comment]
I tested on latest version, it works. Let me push the changes
